### ISSUE TITLE
构建时git检出代码报错

### ISSUE THREAD

**Issue by zhgit** [wdfe/ideploy#9]
git检出代码报错
=================start to build:
=================start to checkout code:
Error: spawn /bin/sh ENOENTError: spawn /bin/sh ENOENT
at _errnoException (util.js:992:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by osanjava** [comment]
遇到同样的问题 mac环境
git checkout stderr:
[2018-11-13 13:54:09] [Error] Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
